<?php
/**
 * @file
 * rbv_relation.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function rbv_relation_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'endpoints'
  $field_bases['endpoints'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'endpoints',
    'foreign keys' => array(),
    'indexes' => array(
      'relation' => array(
        0 => 'entity_type',
        1 => 'entity_id',
        2 => 'r_index',
      ),
    ),
    'locked' => 0,
    'module' => 'relation_endpoint',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'relation_endpoint',
  );

  // Exported field_base: 'field_rel_collaborations'
  $field_bases['field_rel_collaborations'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_rel_collaborations',
    'foreign keys' => array(
      'node' => array(
        'columns' => array(
          'target_id' => 'nid',
        ),
        'table' => 'node',
      ),
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'project' => 'project',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
